rescue => exception
  logger.error(exception.backtrace.join("\n"))
